#!/bin/bash

# ===================================================
# Script Name: menu-zypper
# Author: Dawid Bielecki - dawciobiel
# Date: 2024-12-25
# Version: 1.0
# Description: Bash script used for installing
#              a package or packages using 
#              Zypper Package Manager.
# Usage:
#        ./menu-zypper
# ===================================================

# Source the colors file
source ./colors

# Const
SCRIPT_EXT=".cmd"
SCRIPT_LABEL_LINE=4

# Initialize a counter for the list
counter=1

# Create an array to store the file paths
declare -a files

# Echo empty line
echo -e "\n"

# Loop through all SCRIPT_EXT files in the current directory
for file in *$SCRIPT_EXT; do
  # Ensure the file exists (in case no files match the pattern)
  if [[ -f "$file" ]]; then
    # Read the label line of the file
    label_line=$(sed -n "${SCRIPT_LABEL_LINE}p" "$file" | sed 's/^# //')
    # Print the label line with a numbered list
    echo "$counter. $label_line"
    # Add the file to the array
    files+=("$file")
    # Increment the counter
    ((counter++))
  fi
done

# Check if no files were found
if [[ ${#files[@]} -eq 0 ]]; then
  echo "No $SCRIPT_EXT files found in the current directory."
  exit 1
fi

# Echo empty line
echo

# Prompt the user for input
echo -n "Enter the number of the file you want to execute: "
read choice

# Validate the user input
if [[ $choice =~ ^[0-9]+$ ]] && ((choice > 0 && choice <= ${#files[@]})); then
  # Get the selected file from the array
  selected_file="${files[$((choice-1))]}"
  # Execute the selected file
  bash "$selected_file"
else
  echo "Invalid choice. Exiting."
  exit 1
fi

# Echo new line
echo -e "\n"
